[package]

name = "scribe"
version = "0.5.6"
authors = ["Jordan MacDonald <jordan@wastedintelligence.com>"]
description = "Text editor toolkit."
homepage = "https://github.com/jmacdonald/scribe"
repository = "https://github.com/jmacdonald/scribe"
documentation = "http://jordanmacdonald.ca/rust/scribe"
readme = "README.md"
license-file = "LICENSE"
keywords = ["gap", "buffer", "text", "editor", "document"]

[dependencies]
syntect = "~1.7.1"
luthor = "~0.1.7"
unicode-segmentation = "~1.0.1"
